
server:
  port: 9999

spring:
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    check-template-location: true
  devtools:
    livereload:
      enabled: true
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/sms?serverTimezone=UTC&characterEncoding=UTF-8

    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sms?serverTimezone=UTC&characterEncoding=UTF-8
    username: sms_user
    password: 1523332


